# Generated by Django 6.0 on 2025-12-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(max_length=100)),
                ('search_key', models.TextField()),
                ('exclude_key', models.TextField()),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('site_url', models.CharField(max_length=100)),
            ],
        ),
    ]
