# Generated by Django 6.0 on 2025-12-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_time', models.CharField(max_length=100)),
                ('tender_id', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('search_Key', models.CharField(max_length=100)),
                ('site_link', models.CharField(max_length=100)),
                ('work_description', models.TextField()),
                ('organization_chain', models.CharField(max_length=100)),
                ('bid_submission_end_date', models.CharField(max_length=100)),
                ('bid_submission_end_time', models.CharField(max_length=100)),
                ('tender_value', models.CharField(max_length=100)),
                ('emd_amt', models.CharField(max_length=100)),
                ('tender_fee', models.CharField(max_length=100)),
            ],
        ),
    ]
