# Generated by Django 6.0 on 2025-12-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tenderresults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenderresults',
            old_name='search_Key',
            new_name='search_key',
        ),
    ]
