# Generated by Django 6.0 on 2025-12-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='site_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='site_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
