# Generated by Django 6.0 on 2025-12-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_client_site_url_alter_search_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapercontrol',
            name='searching_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scrapercontrol',
            name='searching_state_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
