# Generated by Django 6.0 on 2025-12-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_scrapercontrol_searching_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapercontrol',
            name='task_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
