# Generated by Django 6.0 on 2025-12-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_scrapercontrol_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapercontrol',
            name='task_id',
        ),
    ]
