# Generated by Django 6.0 on 2026-01-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_scrapercontrol_task_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
