# Generated by Django 6.0 on 2026-01-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='site_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='state_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
