# Generated by Django 6.0 on 2026-01-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_search_site_url_alter_search_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderresults',
            name='emd_amt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tenderresults',
            name='organization_chain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderresults',
            name='search_key',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='tenderresults',
            name='search_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tenderresults',
            name='site_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenderresults',
            name='state_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenderresults',
            name='tender_fee',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenderresults',
            name='tender_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tenderresults',
            name='tender_value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
