# Generated by Django 6.0 on 2026-01-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_tenderresults_emd_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='site_url',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state_name',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='scrapercontrol',
            name='searching_key',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='scrapercontrol',
            name='searching_state_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='site_url',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='state_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
