# Generated by Django 6.0.2 on 2026-02-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_client_site_url_alter_client_state_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderresults',
            name='search_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
