# Generated by Django 6.0.2 on 2026-02-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_tenderresults_search_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderresults',
            name='tender_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
